echo Installing Depends...
pip install customtkinter pyinstaller --quiet
echo Starting Building...

pyinstaller --onefile --windowed --icon=icon.ico --add-data "icon.ico;." --add-data "main.py;." --name WiFi-Home-Server gui.py